print("sfe")
require("giovani.lsp.diagnostics")
vim.o.autocomplete = true

-- langs
require("giovani.lsp.langs.bash")
require("giovani.lsp.langs.c")
require("giovani.lsp.langs.csharp")
require("giovani.lsp.langs.css")
require("giovani.lsp.langs.css_modules")
require("giovani.lsp.langs.docker")
require("giovani.lsp.langs.docker_compose")
require("giovani.lsp.langs.go")
require("giovani.lsp.langs.html")
require("giovani.lsp.langs.json")
require("giovani.lsp.langs.lua")
require("giovani.lsp.langs.python")
require("giovani.lsp.langs.qml")
require("giovani.lsp.langs.rust")
require("giovani.lsp.langs.solidity")
require("giovani.lsp.langs.stylua")
require("giovani.lsp.langs.svelte")
require("giovani.lsp.langs.tailwindcss")
require("giovani.lsp.langs.ts")
